# Generated by Django 3.2 on 2021-04-26 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210426_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr',
            name='id',
        ),
        migrations.RemoveField(
            model_name='kandidat',
            name='id',
        ),
        migrations.AlterField(
            model_name='hr',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='kandidat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user'),
        ),
    ]
