# Generated by Django 3.2 on 2021-04-27 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_auto_20210426_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='status_application', to='vacancies.status_application'),
        ),
    ]
