# Generated by Django 3.2 on 2021-04-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text_answer',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_question',
            field=models.CharField(max_length=1000),
        ),
    ]
