# Generated by Django 3.2 on 2021-04-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_auto_20210428_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='time',
        ),
    ]
