# Generated by Django 3.2 on 2021-05-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0013_alter_result_answer_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
