# Generated by Django 3.2 on 2021-05-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0014_question_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='num',
            field=models.IntegerField(),
        ),
    ]
