# Generated by Django 3.2 on 2021-05-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0015_alter_question_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='quiz',
            name='deadline',
            field=models.IntegerField(default=24),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=500)),
                ('deadline', models.IntegerField(default=24)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_test', to='vacancies.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='Result_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_result', models.CharField(max_length=500)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_Result_test', to='vacancies.application')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_Result_test', to='vacancies.status_test')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_result_test', to='vacancies.test')),
            ],
        ),
    ]
