# Generated by Django 3.2 on 2021-05-07 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0017_alter_result_test_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sait', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128)),
                ('deadline', models.IntegerField(default=24)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Osa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Result_osa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_Result_osa', to='vacancies.application')),
                ('osa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osa_result_osa', to='vacancies.osa')),
            ],
        ),
        migrations.AddField(
            model_name='osa',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_osa', to='vacancies.status_osa'),
        ),
    ]
