# Generated by Django 3.2 on 2021-05-07 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0018_auto_20210507_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='osa',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='osa_application', to='vacancies.osa'),
            preserve_default=False,
        ),
    ]
