# Generated by Django 3.2 on 2021-05-07 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0022_alter_application_osa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='osa',
        ),
    ]
