# Generated by Django 3.2 on 2021-05-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0036_auto_20210509_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(max_length=6000),
        ),
    ]
